version: '3.2'

services:
  faucet:
    image: aresprotocollab/faucet
    container_name: faucet
    build:
      #context: .
      context: https://github.com/aresprotocols/faucet-bot.git
      dockerfile: Dockerfile
    volumes:
      - ./config.toml:/faucet/config.toml
#      - ./src:/faucet/src
    entrypoint: "ts-node src/index.ts"

  redis:
    image: redis:6.2.6
    hostname: redis
    container_name: redis

